services:

    mongo:
        container_name: mongo
        image: mongodb/mongodb-community-server:latest
        ports: 
            - 27017:27017
        restart: always
        environment: 
            - MONGODB_ROOT_PASSWORD=test
            - MONGODB_PORT_NUMBER=27017